### ISSUE TITLE
./test_bandwidth2.out FAILS to run

### ISSUE THREAD

**Issue by matpalm** [TimDettmers/GTX970test#1]
```
dimGrid: 500 500 1. dimBlock: 32 8 1
                  Routine         Bandwidth (GB/s)
                     copy1 0.000000 1.000000
           *** FAILED ***
...
```

see ...
https://gist.github.com/matpalm/fcf734a01964c4e08cd1

unsure how to debug cuda sorry :(

**Comment by TimDettmers** [comment]
Thanks for helping me out with this — much appreciated!

I just pushed a new version which should print the specific error so that we can debug that. One thing you could try is to compile with different compute capabilities and see if the error persists. The GTX970 should support the compile flag -gencode arch=compute_50,code=sm_50.

If the errors persists please post them here.

**Comment by matpalm** [comment]
No worries, thanks for putting all the b other info together. Will have to
run to this tinnitus evening, stay tuned!

**Comment by matpalm** [comment]
runs OK with compute_50,code=sm_50  but much slower. rerunning now...

**Comment by TimDettmers** [comment]
Thank you so much! The first results from the first test look real, so it works. We can see a drop of 20% in performance after the 3.5GB limit, but it is much less drastic than for other benchmarks. I am curious about the second test, but you are right it will take much longer to run that one!

**Comment by matpalm** [comment]
oops, i forgot to mention, the results were in that pull request...
https://github.com/TimDettmers/GTX970test/blob/master/results/test_bandwidth2.output

**Comment by TimDettmers** [comment]
Thanks for all your help, Mat — that really looks like some good data! The decrease is not as large as I thought, so in the end a GTX 970 might be a quite good option. I will update my blog post accordingly in a few days.
